module.exports = `

    allContentfulApplication{
                  edges{
                    node{
                          id
                          title
                          slug
                          actions{
                                id
                                title
                                subTitle
                                slug
                          }
                          appId
                          demoIframeUrl{
                            id
                            demoIframeUrl
                          }
                          requestQuoteUrl{
                            id
                            requestQuoteUrl
                          }
                          tryPageReference{
                            id
                            slug
                          }
                          hideShareButtons
                          solutions{
                                id
                                title
                                slug
                          }
                          supportedPlatforms{
								id
                                title
                                slug
                                icon{
                                  id
                                  square: resolutions(width:120, height:120, quality: 100, resizingBehavior: PAD ){
                                        src
                                        width
                                        height
                                  }
                                }
                          }
                          icon{
                              id
                              square: resolutions(width:120, height:120, quality: 100, resizingBehavior: PAD ){
                                    src
                                    width
                                    height
                              }
                          }    
                          slider{
                                id
                                title
                                image{
                                      id
                                      file{
                                            url
                                      }
                                }
                                video
                          }
                          preview{
                                id
                                preview
                          }  
                          description{
                                id
                                description
                          }   
                           seoMetaData{
                                    id
                                    metaTitle
                                    metaDescription{
                                          id
                                          metaDescription
                                    }
                                    metaKeywords
                                    openGraphTitle
                                    openGraphDescription{
                                          id
                                          openGraphDescription
                                    }
                                    openGraphUrl
                                    openGraphImage{
                                          id
                                          file{
                                              url
                                          }
                                    }
                            }              
                    }
                  }                    
              }  

`;