const contentPageQuery = `content: allContentfulContentPage{
                  edges{
                    node{
                          id
                          title
                          slug
                          titleSection{
                                id
                                title
                                subTitle
                                description{
                                      id
                                      description
                                }
                                image{
                                      id
                                      resolutions(width:247, height:185, quality: 100, resizingBehavior: PAD ){
                                            src
                                            width
                                            height
                                      }
                                }  
                                video                    
                          }
                          contentCollection{
                                id
                                title
                                hideTitle
                                subTitle
                                description{
                                      id
                                      description
                                }
                                image{
                                      id
                                      round: resolutions(width:170, height:170, quality: 100, resizingBehavior: CROP ){
                                            src
                                            width
                                            height
                                      }
                                      standart: resolutions(width:360, height:279, quality: 100, resizingBehavior: PAD ){
                                            src
                                            width
                                            height
                                      }
                                } 
                                link
                                linkText    
                          }
                          hideShareButtons
                          applicationList{
                                id
                                title
                                hideTitle
                                collection{
                                      id
                                      title
                                      preview{
                                            id
                                            preview
                                      }
                                      slug
                                      icon{
                                            id
                                            square: resolutions(width:120, height:120, quality: 100, resizingBehavior: PAD ){
                                                src
                                                width
                                                height
                                            }
                                      }
                                }                            
                          }
                          templatePage
                          templateCollection{
                                id
                                title
                                slug
                          }
                          subMenu{
                                id
                                menuItems{
                                    id
                                    title
                                    slug
                                    reference{
                                      id
                                      slug
                                    }
                                }              
                          }
                          seoMetaData{
                                id
                                metaTitle
                                metaDescription{
                                      id
                                      metaDescription
                                }
                                metaKeywords
                                openGraphTitle
                                openGraphDescription{
                                      id
                                      openGraphDescription
                                }
                                openGraphUrl
                                openGraphImage{
                                      id
                                      file{
                                          url
                                      }
                                }
                          }
                    }
                  }                    
              }`;


export default contentPageQuery;