module.exports = `

    contentfulContactPage( contentful_id: { eq: "4LM4dfjwfuKCkCyKA0uWUE" } ) {
                    id
                    title   
                    slug                
                    iframeForm
                    description{
                        id
                        description
                    }
                    phoneContacts{
                        id
                        title
                        slug
                        email
                        phone
                        color
                        coveringStates{
                            id
                            title
                            shortTitle
                            slug
                        }
                        coveringCountries{
                            id
                            title
                            shortTitle
                            slug
                        }
                        coveringContinents{
                            id
                            title
                            slug
                        }
                        description{
                          id
                          description
                        }
                    }
                    emailContacts{
                        id
                        title
                        slug
                        email
                        phone                        
                        description{
                          id
                          description
                        }
                    }
                    faxContacts{
                        id
                        title
                        slug
                        email
                        phone                        
                        description{
                          id
                          description
                        }
                    }
                    seoMetaData{
                            id
                            metaTitle
                            metaDescription{
                                  id
                                  metaDescription
                            }
                            metaKeywords
                            openGraphTitle
                            openGraphDescription{
                                  id
                                  openGraphDescription
                            }
                            openGraphUrl
                            openGraphImage{
                                  id
                                  file{
                                      url
                                  }
                            }
                    }
              } 

`;